# volterra Environment
variable "projectPrefix" {}
variable "name" {}
variable "environment" {}
variable "sshPublicKey" {}
variable "sshPublicKeyPath" {}
variable "api_p12_file" {}
variable "tenant_name" {}
variable "namespace" {}
variable "delegated_dns_domain" {}
variable "api_url" {}
variable "tags" {}
variable "fleet_label" {}
variable "lb_count" {}
